package com.citi.hackathon_backend.userInfo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "UserInfo")
public class UserInfo {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "user_name")
    private String userName;
    @DynamoDBAttribute(attributeName = "password")
    private String password;
    @DynamoDBAttribute(attributeName = "nick_name")
    private String nickName;
    @DynamoDBAttribute(attributeName = "address")
    private String address;//optional
    @DynamoDBAttribute(attributeName = "email")
    private String email;//optional
    @DynamoDBAttribute(attributeName = "organization")
    private String organization;
    @DynamoDBAttribute(attributeName = "organization_type")
    private String organizationType;
    @DynamoDBAttribute(attributeName = "authority")
    private String authority;

}
