package com.citi.hackathon_backend.document.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.citi.hackathon_backend.event.convert.JsonToListEvents;
import com.citi.hackathon_backend.event.entity.Event;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "Organization")
public class UserDocument {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "authenticationId")
    private String authenticationId;
    //other information;

    @DynamoDBAttribute(attributeName = "create_time")
    private String createTime;

    @DynamoDBAttribute(attributeName = "current_event_position")
    private int currentEventPosition;

    @DynamoDBAttribute(attributeName = "create_user_name")
    private String createUserName;

    @DynamoDBAttribute(attributeName = "events")
    @DynamoDBTypeConverted(converter = JsonToListEvents.class)
    private List<Event> eventList;

}
