package com.citi.hackathon_backend.event.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.citi.hackathon_backend.event.convert.JsonToListEvents;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "Event_table")
public class Event {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "document_id")
    private String documentId;

    @DynamoDBAttribute(attributeName = "organization")
    private String organization;

    @DynamoDBAttribute(attributeName = "assignee")
    private String assignee;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "create_time")
    private String createTime;

    @DynamoDBAttribute(attributeName = "complete_time")
    private String completeTime;

    @DynamoDBAttribute(attributeName = "notification_receiver")
    private String notificationReceiver;

    @DynamoDBAttribute(attributeName = "create_user_name")
    private String createUserName;

    @DynamoDBAttribute(attributeName = "event_index")
    private int eventIndex;

    @DynamoDBAttribute(attributeName = "event_status")
    @DynamoDBTypeConvertedEnum
    private EventStatus eventStatus;


    public String convertToString() {
        return String.format("org:%s, description:%s, create time:%s, event status", this.organization, this.description, this.createTime, this.eventStatus);
    }
}
