package com.citi.hackathon_backend.event.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "Event_table")
public class Event {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "document_id")
    private String documentId;

    @DynamoDBAttribute(attributeName = "organization")
    private String organization;

    @DynamoDBAttribute(attributeName = "current_subEvent_position")
    private int currentSubEventPosition;

    @DynamoDBAttribute(attributeName = "assignee")
    private String assignee;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "create_time")
    private String createTime;

    @DynamoDBAttribute(attributeName = "complete_time")
    private String completeTime;

    @DynamoDBAttribute(attributeName = "notification_receiver")
    private String notificationReceiver;

    @DynamoDBAttribute(attributeName = "subEvents")
    private List<SubEvent> subEventList;

    @DynamoDBAttribute(attributeName = "create_user_name")
    private String createUserName;

    @DynamoDBAttribute(attributeName = "event_index")
    private int eventIndex;

    @DynamoDBAttribute(attributeName = "event_status")
    private EventStatus eventStatus;


    public String convertToString() {
        return String.format("org:%s, description:%s, create time:%s, event status", this.organization, this.description, this.createTime, this.eventStatus);
    }
}
